# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onfido', '0013_populate_received_at_20170112_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='received_at',
            field=models.DateTimeField(help_text='The timestamp when the server received the event.'),
        ),
    ]
